from typing import Protocol

from src.domain.models import Journey, Location, OptimizationResult


class PersistencePort(Protocol):
    def save_location(self, location: Location) -> None: ...
    def get_location(self, location_id: str) -> Location: ...
    def list_locations(self) -> list[Location]: ...
    def delete_location(self, location_id: str) -> bool: ...
    def save_journey(self, journey: Journey) -> None: ...
    def get_journey(self, journey_id: str) -> Journey: ...
    def list_journeys(self) -> list[Journey]: ...
    def save_result(self, result: OptimizationResult) -> None: ...
    def get_result(self, result_id: str) -> OptimizationResult: ...
